// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToyStore.Infrastructure.Persistence;

#nullable disable

namespace ToyStore.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260716235231_AddCatalogFoundation")]
    partial class AddCatalogFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ToyStore.Domain.Catalog.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ArchivedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedEnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedDisplayName")
                        .IsUnique()
                        .HasDatabaseName("UX_Brands_NormalizedDisplayName");

                    b.HasIndex("NormalizedEnglishName")
                        .IsUnique()
                        .HasDatabaseName("UX_Brands_NormalizedEnglishName");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Brands_Slug");

                    b.ToTable("Brands", null, t =>
                        {
                            t.HasCheckConstraint("CK_Brands_Image_AllNullOrPresent", "(\"ImageStorageKey\" IS NULL AND \"ImagePublicRelativeUrl\" IS NULL AND \"ImageAltText\" IS NULL) OR (\"ImageStorageKey\" IS NOT NULL AND \"ImageStorageKey\" ~ '[^[:space:]]' AND \"ImagePublicRelativeUrl\" IS NOT NULL AND \"ImagePublicRelativeUrl\" ~ '[^[:space:]]' AND \"ImageAltText\" IS NOT NULL AND \"ImageAltText\" ~ '[^[:space:]]')");

                            t.HasCheckConstraint("CK_Brands_Slug_Format", "\"Slug\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("ToyStore.Domain.Catalog.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_Characters_UniverseId_NormalizedName");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("ToyStore.Domain.Catalog.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductCategories_Code");

                    b.ToTable("ProductCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "ArtToy"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "Gundam"
                        });
                });

            modelBuilder.Entity("ToyStore.Domain.Catalog.Universe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ArchivedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedEnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedDisplayName")
                        .IsUnique()
                        .HasDatabaseName("UX_Universes_NormalizedDisplayName");

                    b.HasIndex("NormalizedEnglishName")
                        .IsUnique()
                        .HasDatabaseName("UX_Universes_NormalizedEnglishName");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Universes_Slug");

                    b.ToTable("Universes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Universes_Logo_AllNullOrPresent", "(\"LogoStorageKey\" IS NULL AND \"LogoPublicRelativeUrl\" IS NULL AND \"LogoAltText\" IS NULL) OR (\"LogoStorageKey\" IS NOT NULL AND \"LogoStorageKey\" ~ '[^[:space:]]' AND \"LogoPublicRelativeUrl\" IS NOT NULL AND \"LogoPublicRelativeUrl\" ~ '[^[:space:]]' AND \"LogoAltText\" IS NOT NULL AND \"LogoAltText\" ~ '[^[:space:]]')");

                            t.HasCheckConstraint("CK_Universes_Slug_Format", "\"Slug\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:catalog-seed",
                            DisplayName = "Marvel",
                            EnglishName = "Marvel",
                            NormalizedDisplayName = "MARVEL",
                            NormalizedEnglishName = "MARVEL",
                            Slug = "marvel",
                            Status = "Active",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system:catalog-seed"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:catalog-seed",
                            DisplayName = "DC",
                            EnglishName = "DC",
                            NormalizedDisplayName = "DC",
                            NormalizedEnglishName = "DC",
                            Slug = "dc",
                            Status = "Active",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system:catalog-seed"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:catalog-seed",
                            DisplayName = "Unknown",
                            EnglishName = "Unknown",
                            NormalizedDisplayName = "UNKNOWN",
                            NormalizedEnglishName = "UNKNOWN",
                            Slug = "unknown",
                            Status = "Active",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system:catalog-seed"
                        });
                });

            modelBuilder.Entity("ToyStore.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ArchivedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedEnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SaleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("NormalizedDisplayName")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_NormalizedDisplayName");

                    b.HasIndex("NormalizedEnglishName")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_NormalizedEnglishName");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_Slug");

                    b.HasIndex("UniverseId");

                    b.HasIndex("Status", "SaleType")
                        .HasDatabaseName("IX_Products_Status_SaleType");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_InStock_Price", "\"InStockPrice\" IS NULL OR \"InStockPrice\" > 0");

                            t.HasCheckConstraint("CK_Products_Offer_Matches_SaleType", "(\"SaleType\" = 'InStock' AND \"InStockPrice\" IS NOT NULL AND \"PreOrderFullPrice\" IS NULL AND \"PreOrderDepositAmount\" IS NULL AND \"PreOrderCloseAtUtc\" IS NULL AND \"PreOrderEstimatedArrivalMonth\" IS NULL AND \"PreOrderEstimatedArrivalYear\" IS NULL AND \"PreOrderTotalCapacity\" IS NULL AND \"PreOrderMaxPerCustomer\" IS NULL AND \"PreOrderBalancePaymentDays\" IS NULL) OR (\"SaleType\" = 'PreOrder' AND \"InStockPrice\" IS NULL AND \"PreOrderFullPrice\" IS NOT NULL AND \"PreOrderDepositAmount\" IS NOT NULL AND \"PreOrderCloseAtUtc\" IS NOT NULL AND \"PreOrderEstimatedArrivalMonth\" IS NOT NULL AND \"PreOrderEstimatedArrivalYear\" IS NOT NULL AND \"PreOrderTotalCapacity\" IS NOT NULL AND \"PreOrderMaxPerCustomer\" IS NOT NULL AND \"PreOrderBalancePaymentDays\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Products_PreOrder_Amounts", "\"PreOrderFullPrice\" IS NULL OR (\"PreOrderFullPrice\" > 0 AND \"PreOrderDepositAmount\" > 0 AND \"PreOrderDepositAmount\" < \"PreOrderFullPrice\")");

                            t.HasCheckConstraint("CK_Products_PreOrder_BalancePaymentDays", "\"PreOrderBalancePaymentDays\" IS NULL OR \"PreOrderBalancePaymentDays\" > 0");

                            t.HasCheckConstraint("CK_Products_PreOrder_BangkokCloseTime", "\"PreOrderCloseAtUtc\" IS NULL OR (\"PreOrderCloseAtUtc\" AT TIME ZONE 'Asia/Bangkok')::time = TIME '23:59:59'");

                            t.HasCheckConstraint("CK_Products_PreOrder_Capacity", "\"PreOrderTotalCapacity\" IS NULL OR (\"PreOrderTotalCapacity\" > 0 AND \"PreOrderMaxPerCustomer\" > 0 AND \"PreOrderMaxPerCustomer\" <= \"PreOrderTotalCapacity\")");

                            t.HasCheckConstraint("CK_Products_PreOrder_CloseAfterCreated", "\"PreOrderCloseAtUtc\" IS NULL OR \"PreOrderCloseAtUtc\" > \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_Products_PreOrder_EstimatedArrival", "\"PreOrderEstimatedArrivalMonth\" IS NULL OR (\"PreOrderEstimatedArrivalMonth\" BETWEEN 1 AND 12 AND \"PreOrderEstimatedArrivalYear\" BETWEEN 1 AND 9999)");

                            t.HasCheckConstraint("CK_Products_PreOrder_EtaNotBeforeCloseMonth", "\"PreOrderCloseAtUtc\" IS NULL OR (\"PreOrderEstimatedArrivalYear\", \"PreOrderEstimatedArrivalMonth\") >= (EXTRACT(YEAR FROM \"PreOrderCloseAtUtc\" AT TIME ZONE 'Asia/Bangkok'), EXTRACT(MONTH FROM \"PreOrderCloseAtUtc\" AT TIME ZONE 'Asia/Bangkok'))");

                            t.HasCheckConstraint("CK_Products_Slug_Format", "\"Slug\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("ToyStore.Domain.Products.ProductCharacter", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("ProductCharacters", (string)null);
                });

            modelBuilder.Entity("ToyStore.Domain.Products.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicRelativeUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductImages_ProductId_Primary")
                        .HasFilter("\"IsPrimary\"");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductImages_StorageKey");

                    b.HasIndex("ProductId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductImages_ProductId_SortOrder");

                    b.ToTable("ProductImages", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductImages_PrimaryMatchesOrder", "\"IsPrimary\" = (\"SortOrder\" = 0)");

                            t.HasCheckConstraint("CK_ProductImages_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("ToyStore.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ToyStore.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ToyStore.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyStore.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ToyStore.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToyStore.Domain.Catalog.Brand", b =>
                {
                    b.OwnsOne("ToyStore.Domain.Catalog.CatalogMediaReference", "Image", b1 =>
                        {
                            b1.Property<Guid>("BrandId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AltText")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("ImageAltText");

                            b1.Property<string>("PublicRelativeUrl")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("ImagePublicRelativeUrl");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("ImageStorageKey");

                            b1.HasKey("BrandId");

                            b1.ToTable("Brands");

                            b1.WithOwner()
                                .HasForeignKey("BrandId");
                        });

                    b.Navigation("Image");
                });

            modelBuilder.Entity("ToyStore.Domain.Catalog.Character", b =>
                {
                    b.HasOne("ToyStore.Domain.Catalog.Universe", null)
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ToyStore.Domain.Catalog.Universe", b =>
                {
                    b.OwnsOne("ToyStore.Domain.Catalog.CatalogMediaReference", "Logo", b1 =>
                        {
                            b1.Property<Guid>("UniverseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AltText")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("LogoAltText");

                            b1.Property<string>("PublicRelativeUrl")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("LogoPublicRelativeUrl");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("LogoStorageKey");

                            b1.HasKey("UniverseId");

                            b1.ToTable("Universes");

                            b1.WithOwner()
                                .HasForeignKey("UniverseId");
                        });

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("ToyStore.Domain.Products.Product", b =>
                {
                    b.HasOne("ToyStore.Domain.Catalog.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToyStore.Domain.Catalog.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToyStore.Domain.Catalog.Universe", null)
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ToyStore.Domain.Products.InStockOffer", "InStockOffer", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Price")
                                .HasColumnType("numeric")
                                .HasColumnName("InStockPrice");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("ToyStore.Domain.Products.PreOrderOffer", "PreOrderOffer", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BalancePaymentDays")
                                .HasColumnType("integer")
                                .HasColumnName("PreOrderBalancePaymentDays");

                            b1.Property<DateTimeOffset>("CloseAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PreOrderCloseAtUtc");

                            b1.Property<decimal>("DepositAmount")
                                .HasColumnType("numeric")
                                .HasColumnName("PreOrderDepositAmount");

                            b1.Property<int>("EstimatedArrivalMonth")
                                .HasColumnType("integer")
                                .HasColumnName("PreOrderEstimatedArrivalMonth");

                            b1.Property<int>("EstimatedArrivalYear")
                                .HasColumnType("integer")
                                .HasColumnName("PreOrderEstimatedArrivalYear");

                            b1.Property<decimal>("FullPrice")
                                .HasColumnType("numeric")
                                .HasColumnName("PreOrderFullPrice");

                            b1.Property<int>("MaxPerCustomer")
                                .HasColumnType("integer")
                                .HasColumnName("PreOrderMaxPerCustomer");

                            b1.Property<int>("TotalCapacity")
                                .HasColumnType("integer")
                                .HasColumnName("PreOrderTotalCapacity");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("InStockOffer");

                    b.Navigation("PreOrderOffer");
                });

            modelBuilder.Entity("ToyStore.Domain.Products.ProductCharacter", b =>
                {
                    b.HasOne("ToyStore.Domain.Catalog.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToyStore.Domain.Products.Product", null)
                        .WithMany("Characters")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToyStore.Domain.Products.ProductImage", b =>
                {
                    b.HasOne("ToyStore.Domain.Products.Product", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToyStore.Domain.Products.Product", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
