namespace ToyStore.Domain.Inventory;

public enum InventoryRule
{
    InventoryIdentityRequired,
    ProductIdentityRequired,
    MovementIdentityRequired,
    ReservationIdentityRequired,
    CheckoutAttemptIdentityRequired,
    QuantityCannotBeNegative,
    QuantityMustBePositive,
    AdjustmentCannotBeZero,
    QuantityOverflow,
    InsufficientOnHand,
    InsufficientReservableQuantity,
    HeldQuantityInvariant,
    AuditInstantMustBeUtc,
    AuditTimeWentBackwards,
    ActorRequired,
    ActorTooLong,
    ReasonRequired,
    ReasonTooLong,
    ReferenceRequired,
    ReferenceTooLong,
    ConcurrencyVersionMismatch,
    ConcurrencyVersionExhausted,
    ReservationExpiryInvalid,
    ReservationInventoryMismatch,
    ReservationProductMismatch,
    ReservationTransitionInvalid,
    ReservationEvidenceConflict,
    ReservationExpireTooEarly,
    ReservationIdentityDuplicate,
    AvailabilitySnapshotInvalid,
}
