namespace ToyStore.UnitTests.Infrastructure;

public sealed class CatalogCleanupMigrationArtifactTests
{
    [Fact]
    public void IdempotentDeltaContainsOnlyVersionsAndCleanupLedger()
    {
        var sql = File.ReadAllText(Path.Combine(
            RepositoryRoot(),
            "artifacts",
            "migrations",
            "AddCatalogCleanupLedger.sql"));

        Assert.Contains("ALTER TABLE \"Brands\" ADD \"Version\" bigint NOT NULL DEFAULT 1", sql, StringComparison.Ordinal);
        Assert.Contains("ALTER TABLE \"Universes\" ADD \"Version\" bigint NOT NULL DEFAULT 1", sql, StringComparison.Ordinal);
        Assert.Contains("CREATE TABLE \"MediaCleanupEntries\"", sql, StringComparison.Ordinal);
        Assert.Contains("\"ResolvedAtUtc\" IS NULL", sql, StringComparison.Ordinal);
        Assert.DoesNotContain("DROP ", sql, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("ALTER TABLE \"AspNet", sql, StringComparison.Ordinal);
        Assert.DoesNotContain("DELETE FROM", sql, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("GENERATED BY DEFAULT AS IDENTITY", sql, StringComparison.Ordinal);
    }

    private static string RepositoryRoot()
    {
        for (var current = new DirectoryInfo(AppContext.BaseDirectory);
             current is not null;
             current = current.Parent)
        {
            if (File.Exists(Path.Combine(current.FullName, "ToyStore.sln")))
            {
                return current.FullName;
            }
        }

        throw new DirectoryNotFoundException("Could not locate ToyStore.sln.");
    }
}
