namespace ToyStore.Domain.PreOrders;

public enum PreOrderCapacityRule
{
    CapacityIdentityRequired,
    ProductIdentityRequired,
    MovementIdentityRequired,
    ReservationIdentityRequired,
    CheckoutAttemptIdentityRequired,
    CustomerIdentityRequired,
    QuantityMustBePositive,
    TotalCapacityBelowAllocated,
    QuantityOverflow,
    InsufficientRemainingCapacity,
    HeldQuantityInvariant,
    CommittedQuantityInvariant,
    CapacityAccountingInvariant,
    PreOrderClosed,
    ReservationExpiryInvalid,
    ReservationCapacityMismatch,
    ReservationProductMismatch,
    ReservationTransitionInvalid,
    ReservationEvidenceConflict,
    ReservationExpireTooEarly,
    CancellationKindInvalid,
    AuditInstantMustBeUtc,
    AuditTimeWentBackwards,
    ActorRequired,
    ActorTooLong,
    CustomerTooLong,
    ReasonRequired,
    ReasonTooLong,
    ReferenceRequired,
    ReferenceTooLong,
    ConcurrencyVersionMismatch,
    ConcurrencyVersionExhausted,
}
